// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $index from "./routes/index.tsx";
import * as $projects_chip8_index from "./routes/projects/chip8/index.tsx";
import * as $projects_cinemraft_index from "./routes/projects/cinemraft/index.tsx";
import * as $projects_gol_index from "./routes/projects/gol/index.tsx";
import * as $projects_index from "./routes/projects/index.tsx";
import * as $projects_tetris_index from "./routes/projects/tetris/index.tsx";
import * as $Rust from "./islands/Rust.tsx";
import * as $projects_Chip8Component from "./islands/projects/Chip8Component.tsx";
import * as $projects_CinemraftComponent from "./islands/projects/CinemraftComponent.tsx";
import * as $projects_GameOfLifeComponent from "./islands/projects/GameOfLifeComponent.tsx";
import * as $projects_TetrisComponent from "./islands/projects/TetrisComponent.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/api/joke.ts": $api_joke,
    "./routes/index.tsx": $index,
    "./routes/projects/chip8/index.tsx": $projects_chip8_index,
    "./routes/projects/cinemraft/index.tsx": $projects_cinemraft_index,
    "./routes/projects/gol/index.tsx": $projects_gol_index,
    "./routes/projects/index.tsx": $projects_index,
    "./routes/projects/tetris/index.tsx": $projects_tetris_index,
  },
  islands: {
    "./islands/Rust.tsx": $Rust,
    "./islands/projects/Chip8Component.tsx": $projects_Chip8Component,
    "./islands/projects/CinemraftComponent.tsx": $projects_CinemraftComponent,
    "./islands/projects/GameOfLifeComponent.tsx": $projects_GameOfLifeComponent,
    "./islands/projects/TetrisComponent.tsx": $projects_TetrisComponent,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
